### ISSUE TITLE
Parsing Error

### ISSUE THREAD

**Issue by Irazall** [hefeleal/whatsappStatistics#1]
Thanks for this nice tool! I tried it out but I have the following error while starting an usual command like the one below

```
~/IdeaProjects/whatsappStatistics$ python3 analyze.py -lm 'WhatsApp Chat with xy.txt' 
Traceback (most recent call last):
  File "analyze.py", line 336, in <module>
    msgs = parse_file(args.file)
  File "analyze.py", line 41, in parse_file
    msgs[len(msgs)-1].what += "\n" + c[:-1]
IndexError: list index out of range
```

Why is this happening? Is it maybe because the format changed in the last 8 months? How can I debug this code? I am rather a beginner using code from GitHub

Thank you so much in advance!

**Comment by hefeleal** [comment]
Hi, sorry for the late response. The code had problems parsing files that start with newlines. I fixed the issue here: https://github.com/hefeleal/whatsappStatistics/commit/ce28ad386549d14792bb539d2bbffafc692bc40f#diff-a24b48d276b201e75736c0d0c67c70a7R41 Please try again :)
